### ISSUE TITLE
Fully uninstall edge or leave it intact

### ISSUE THREAD

**Issue by idontusenumbers** [CFCC/TurboStacks#10]
**Situation:**
An attempt has been made to replace Edge (Tasman) with Chrome. The removal of Edge was incomplete and leaves behind a stub that steals 'Default Browser' from Chrome, but the leftover stub can't even load web pages, this leads to crazy errors when clicking shortcuts or URLs in other programs.

**Target:**
Working system-wide browser without error messages; Ideally one which does not have compatibility problems.

**Proposal:**
Leave Edge (now Chromium) intact and the default. It's faster, uses less power, and is fully compatible with Chrome. You end up sending telemetry to Microsoft instead of Google, which Charlie thinks at this point in computer history is a better choice.

**Comment by cohoe** [comment]
Wrong repo. Moved to https://github.com/CFCC/TurboPuppet/issues/45
